import { StyleSheet } from 'react-native';
import { colors, spacing, radius, shadow, typography } from '../../theme';

export const m = StyleSheet.create({
  overlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.45)', justifyContent: 'flex-end' },
  sheet: { backgroundColor: colors.surface, borderTopLeftRadius: radius.xl, borderTopRightRadius: radius.xl, padding: spacing.xxl, paddingBottom: 36, maxHeight: '92%' },
  handle: { width: 36, height: 4, borderRadius: 2, backgroundColor: colors.border, alignSelf: 'center', marginBottom: spacing.xl },
  title: { ...typography.h2, color: colors.textPrimary, marginBottom: spacing.xl },
  label: { ...typography.caption, color: colors.textSecondary, fontWeight: '600', textTransform: 'uppercase', letterSpacing: 0.5, marginBottom: spacing.sm },
  input: { backgroundColor: colors.background, borderWidth: 1.5, borderColor: colors.border, borderRadius: radius.md, paddingHorizontal: spacing.lg, paddingVertical: spacing.md, fontSize: 15, color: colors.textPrimary, marginBottom: spacing.lg, minHeight: 50 },
  textarea: { minHeight: 80, textAlignVertical: 'top', paddingTop: spacing.md },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm, marginBottom: spacing.lg },
  chip: { paddingHorizontal: spacing.md, paddingVertical: spacing.sm, borderRadius: radius.sm, backgroundColor: colors.background, borderWidth: 1, borderColor: colors.border, marginRight: spacing.sm, marginBottom: spacing.sm },
  chipActive: { backgroundColor: colors.primary, borderColor: colors.primary },
  chipText: { ...typography.bodySmall, color: colors.textSecondary, fontWeight: '500' },
  chipTextActive: { color: '#fff', fontWeight: '600' },
  splitRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, marginBottom: spacing.sm },
  splitName: { width: 90, ...typography.bodySmall, color: colors.textPrimary, fontWeight: '500' },
  splitInput: { flex: 1, backgroundColor: colors.background, borderWidth: 1, borderColor: colors.border, borderRadius: radius.sm, paddingHorizontal: spacing.md, paddingVertical: spacing.sm, fontSize: 14, color: colors.textPrimary, minHeight: 40 },
  actions: { flexDirection: 'row', gap: spacing.sm, marginTop: spacing.md, flexWrap: 'wrap' },
  cancelBtn: { flex: 1, paddingVertical: spacing.md, borderRadius: radius.md, backgroundColor: colors.background, borderWidth: 1, borderColor: colors.border, alignItems: 'center', minWidth: 80 },
  cancelText: { ...typography.body, color: colors.textSecondary, fontWeight: '600' },
  submitBtn: { flex: 2, paddingVertical: spacing.md, borderRadius: radius.md, backgroundColor: colors.primary, alignItems: 'center', minWidth: 100, ...shadow.sm },
  submitText: { ...typography.body, color: '#fff', fontWeight: '700' },
  deleteBtn: { paddingVertical: spacing.md, paddingHorizontal: spacing.lg, borderRadius: radius.md, backgroundColor: colors.errorLight, borderWidth: 1, borderColor: colors.errorBorder, alignItems: 'center' },
  deleteBtnText: { ...typography.body, color: colors.error, fontWeight: '600' },
  memberRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: spacing.md, borderBottomWidth: 1, borderBottomColor: colors.border, gap: spacing.md },
  memberRowAvatar: { width: 40, height: 40, borderRadius: radius.full, backgroundColor: colors.primaryLight, justifyContent: 'center', alignItems: 'center' },
  memberRowAvatarText: { ...typography.h3, color: colors.primary, fontWeight: '700' },
  memberRowName: { ...typography.body, color: colors.textPrimary, fontWeight: '600' },
  memberRowEmail: { ...typography.caption, color: colors.textSecondary },
  addBtn: { paddingHorizontal: spacing.md, paddingVertical: spacing.sm, borderRadius: radius.sm, backgroundColor: colors.primary },
  addBtnText: { ...typography.caption, color: '#fff', fontWeight: '700' },
});
